version: "3.9"

volumes:
  data:

services:
  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - ./db.env

  app:
    build:
      context: .

    command: bash -c "/home/hotel_admin/entrypoint.sh"

    ports:
      - 8000:8000

    volumes:
      - ./src:/home/hotel_admin/code

    env_file:
      - ./src/.env
      - ./db.env

    depends_on:
      - db

  rabbitmq:
    image: rabbitmq:3.10-alpine
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
