# Generated by Django 4.1 on 2022-08-31 10:59

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_refund',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 8, 31, 10, 59, 53, 33541, tzinfo=datetime.timezone.utc))]),
        ),
    ]
