# Generated by Django 4.1 on 2022-09-01 12:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_alter_reservation_created_alter_reservation_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
