# Generated by Django 4.1 on 2022-08-31 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='discount_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
